/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleUsesRouteImport } from './routes/$locale/uses'
import { Route as LocaleOssRouteImport } from './routes/$locale/oss'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleBookRouteImport } from './routes/$locale/book'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleCasesIndexRouteImport } from './routes/$locale/cases/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleCasesSlugRouteImport } from './routes/$locale/cases/$slug'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleUsesRoute = LocaleUsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleOssRoute = LocaleOssRouteImport.update({
  id: '/oss',
  path: '/oss',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBookRoute = LocaleBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCasesIndexRoute = LocaleCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCasesSlugRoute = LocaleCasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/book': typeof LocaleBookRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/oss': typeof LocaleOssRoute
  '/$locale/uses': typeof LocaleUsesRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/cases/$slug': typeof LocaleCasesSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/cases/': typeof LocaleCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/book': typeof LocaleBookRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/oss': typeof LocaleOssRoute
  '/$locale/uses': typeof LocaleUsesRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/cases/$slug': typeof LocaleCasesSlugRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/cases': typeof LocaleCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/book': typeof LocaleBookRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/oss': typeof LocaleOssRoute
  '/$locale/uses': typeof LocaleUsesRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/cases/$slug': typeof LocaleCasesSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/cases/': typeof LocaleCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/book'
    | '/$locale/contact'
    | '/$locale/oss'
    | '/$locale/uses'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/cases/$slug'
    | '/$locale/blog/'
    | '/$locale/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale/book'
    | '/$locale/contact'
    | '/$locale/oss'
    | '/$locale/uses'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/cases/$slug'
    | '/$locale/blog'
    | '/$locale/cases'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/book'
    | '/$locale/contact'
    | '/$locale/oss'
    | '/$locale/uses'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/cases/$slug'
    | '/$locale/blog/'
    | '/$locale/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/uses': {
      id: '/$locale/uses'
      path: '/uses'
      fullPath: '/$locale/uses'
      preLoaderRoute: typeof LocaleUsesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/oss': {
      id: '/$locale/oss'
      path: '/oss'
      fullPath: '/$locale/oss'
      preLoaderRoute: typeof LocaleOssRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/book': {
      id: '/$locale/book'
      path: '/book'
      fullPath: '/$locale/book'
      preLoaderRoute: typeof LocaleBookRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/cases/': {
      id: '/$locale/cases/'
      path: '/cases'
      fullPath: '/$locale/cases/'
      preLoaderRoute: typeof LocaleCasesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/cases/$slug': {
      id: '/$locale/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/$locale/cases/$slug'
      preLoaderRoute: typeof LocaleCasesSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleBookRoute: typeof LocaleBookRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleOssRoute: typeof LocaleOssRoute
  LocaleUsesRoute: typeof LocaleUsesRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleCasesSlugRoute: typeof LocaleCasesSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleCasesIndexRoute: typeof LocaleCasesIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleBookRoute: LocaleBookRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleOssRoute: LocaleOssRoute,
  LocaleUsesRoute: LocaleUsesRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleCasesSlugRoute: LocaleCasesSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleCasesIndexRoute: LocaleCasesIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
